server:
  port: 8020
  servlet:
    context-path: /user-service-api
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-bp10c9m597111126xeo.mysql.rds.aliyuncs.com:3306/user
      username: minggui98
      password: 7hV#7612
      max-active: 5
      max-wait: 10000
  redis:
    host: blog.minggui98.vip
    password: 7hV#7612
eureka:
  client:
    service-url:
      defaultZone: http://47.96.173.42:8761/eureka,http://47.96.173.42:8761/eureka

