server:
  port: 8020
  servlet:
    context-path: /user-service-api
spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:file:./user
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://47.96.173.42:8761/eureka,http://47.96.173.42:8761/eureka
