spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/article?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 7hV#7612
      max-active: 5
      max-wait: 10000
  redis:
    host: 127.0.0.1
    password: 7hV#7612
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
