spring:
  application:
    name: register-center-server
server:
  port: 8763
eureka:
  instance:
    hostname: register-center-3.minggui98.vip
    environment: server3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register-center-1.minggui98.vip:8761/eureka,http://register-center-2.minggui98.vip:8762/eureka
