spring:
  application:
    name: register-center-server2
  profiles:
    active: dev
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka