spring:
  application:
    name: register-center-server
server:
  port: 8761
eureka:
  instance:
    hostname: register-center-1.minggui98.vip
    environment: server1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register-center-2.minggui98.vip:8762/eureka,http://register-center-3.minggui98.vip:8763/eureka
