spring:
  application:
    name: register-center-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka,http://${eureka.instance.hostname}:8763/eureka
