spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-bp10c9m597111126xeo.mysql.rds.aliyuncs.com:3306/blog
      username: minggui98
      password: 7hV#7612
      max-active: 5
      max-wait: 10000
  freemarker:
    suffix: .ftl
  redis:
    host: localhost
    password: 7hV#7612
    port: 6379
  cache:
    cache-names: article
    redis:
      use-key-prefix: true
    type: redis
server:
  port: 8080
