server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://blog.minggui98.vip:8761/eureka/,http://blog.minggui98.vip:8762/eureka/
