server:
  port: 8080
spring:
  application:
    name: admin
  freemarker:
    suffix: .ftl
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis
  redis:
    host: localhost
    password: 7hV#7612
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
