spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 7Hv#7612
      max-active: 5
      max-wait: 10000
  redis:
    host: 127.0.0.1
    password: 7Hv#7612
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    hostname: localhost
mybatis-plus:
  type-aliases-package: org.mg.blog.model,org.mg.blog.system.dto
  mapper-locations: classpath:mapper/*Mapper.xml
