spring:
  freemarker:
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: minggui98
    password: 7hV#7612
    url: jdbc:mysql://rm-bp10c9m597111126xeo.mysql.rds.aliyuncs.com:3306/blog
server:
  port: 80
mybatis:
  type-aliases-package: org.mg.blog.model
