server:
  port: 8888
  servlet:
    context-path: /config-center
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liminggui98/mg-blog.git
          search-paths: config-repo/
  application:
    name: config-center
eureka:
  client:
    service-url:
      defaultZone: http://register-center-1.minggui98.vip:8761/eureka,http://register-center-2.minggui98.vip:8762/eureka,http://register-center-3.minggui98.vip:8763/eureka
management:
  endpoints:
    web:
      exposure:
        include: [ 'beans','info','health','env','refresh','mappings' ]
